# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vis.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1213, 810)
        Form.setStyleSheet("")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(50, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setObjectName("label1")
        self.cam_num = QtWidgets.QComboBox(Form)
        self.cam_num.setGeometry(QtCore.QRect(50, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.cam_num.setFont(font)
        self.cam_num.setObjectName("cam_num")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(50, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.startFrame = QtWidgets.QComboBox(Form)
        self.startFrame.setGeometry(QtCore.QRect(50, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.startFrame.setFont(font)
        self.startFrame.setObjectName("startFrame")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.startFrame.addItem("")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(50, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.endFrame = QtWidgets.QComboBox(Form)
        self.endFrame.setGeometry(QtCore.QRect(50, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.endFrame.setFont(font)
        self.endFrame.setObjectName("endFrame")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(50, 450, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.okButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon)
        self.okButton.setObjectName("okButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 760, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(50, 490, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.startButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(50, 530, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.stopButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.lefttop_widget = QtWidgets.QWidget(Form)
        self.lefttop_widget.setGeometry(QtCore.QRect(30, 120, 151, 231))
        self.lefttop_widget.setObjectName("lefttop_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.lefttop_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lefttop_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lefttop_Layout.setContentsMargins(0, 0, 0, 0)
        self.lefttop_Layout.setObjectName("lefttop_Layout")
        self.leftdown_widget = QtWidgets.QWidget(Form)
        self.leftdown_widget.setGeometry(QtCore.QRect(30, 430, 151, 151))
        self.leftdown_widget.setObjectName("leftdown_widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.leftdown_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 151, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.leftdown_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.leftdown_Layout.setContentsMargins(0, 0, 0, 0)
        self.leftdown_Layout.setObjectName("leftdown_Layout")
        self.right_widget = QtWidgets.QWidget(Form)
        self.right_widget.setGeometry(QtCore.QRect(200, 20, 1001, 781))
        self.right_widget.setObjectName("right_widget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.right_widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1001, 781))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.right_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.right_Layout.setContentsMargins(1, 1, 1, 1)
        self.right_Layout.setSpacing(3)
        self.right_Layout.setObjectName("right_Layout")
        self.videoBox = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox.setText("")
        self.videoBox.setObjectName("videoBox")
        self.right_Layout.addWidget(self.videoBox, 0, 0, 1, 1)
        self.videoBox_heatmap = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox_heatmap.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox_heatmap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox_heatmap.setText("")
        self.videoBox_heatmap.setObjectName("videoBox_heatmap")
        self.right_Layout.addWidget(self.videoBox_heatmap, 1, 0, 1, 1)
        self.videoBox_traj = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox_traj.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox_traj.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox_traj.setText("")
        self.videoBox_traj.setObjectName("videoBox_traj")
        self.right_Layout.addWidget(self.videoBox_traj, 0, 1, 1, 1)
        self.exit_Button = QtWidgets.QPushButton(Form)
        self.exit_Button.setGeometry(QtCore.QRect(30, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.exit_Button.setFont(font)
        self.exit_Button.setObjectName("exit_Button")
        self.min_Button = QtWidgets.QPushButton(Form)
        self.min_Button.setGeometry(QtCore.QRect(70, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.min_Button.setFont(font)
        self.min_Button.setObjectName("min_Button")
        self.info_widget = QtWidgets.QWidget(Form)
        self.info_widget.setGeometry(QtCore.QRect(10, 690, 191, 111))
        self.info_widget.setObjectName("info_widget")
        self.window_widget = QtWidgets.QWidget(Form)
        self.window_widget.setGeometry(QtCore.QRect(30, 30, 81, 41))
        self.window_widget.setObjectName("window_widget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.window_widget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.window_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.window_Layout.setContentsMargins(0, 0, 0, 0)
        self.window_Layout.setObjectName("window_Layout")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setGeometry(QtCore.QRect(10, 20, 191, 671))
        self.main_widget.setObjectName("main_widget")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 671))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.main_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.main_Layout.setContentsMargins(0, 0, 0, 0)
        self.main_Layout.setObjectName("main_Layout")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 690, 191, 111))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.info_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.info_Layout.setContentsMargins(0, 0, 0, 0)
        self.info_Layout.setObjectName("info_Layout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "Camera"))
        self.cam_num.setCurrentText(_translate("Form", "1"))
        self.cam_num.setItemText(0, _translate("Form", "1"))
        self.cam_num.setItemText(1, _translate("Form", "2"))
        self.cam_num.setItemText(2, _translate("Form", "3"))
        self.cam_num.setItemText(3, _translate("Form", "4"))
        self.cam_num.setItemText(4, _translate("Form", "5"))
        self.cam_num.setItemText(5, _translate("Form", "6"))
        self.cam_num.setItemText(6, _translate("Form", "7"))
        self.cam_num.setItemText(7, _translate("Form", "8"))
        self.label2.setText(_translate("Form", "Start Frame"))
        self.startFrame.setItemText(0, _translate("Form", "0"))
        self.startFrame.setItemText(1, _translate("Form", "8000"))
        self.startFrame.setItemText(2, _translate("Form", "16000"))
        self.startFrame.setItemText(3, _translate("Form", "24000"))
        self.startFrame.setItemText(4, _translate("Form", "32000"))
        self.startFrame.setItemText(5, _translate("Form", "40000"))
        self.startFrame.setItemText(6, _translate("Form", "48000"))
        self.startFrame.setItemText(7, _translate("Form", "56000"))
        self.startFrame.setItemText(8, _translate("Form", "64000"))
        self.startFrame.setItemText(9, _translate("Form", "72000"))
        self.startFrame.setItemText(10, _translate("Form", "80000"))
        self.label3.setText(_translate("Form", "End Frame"))
        self.endFrame.setItemText(0, _translate("Form", "100"))
        self.endFrame.setItemText(1, _translate("Form", "8000"))
        self.endFrame.setItemText(2, _translate("Form", "16000"))
        self.endFrame.setItemText(3, _translate("Form", "24000"))
        self.endFrame.setItemText(4, _translate("Form", "32000"))
        self.endFrame.setItemText(5, _translate("Form", "40000"))
        self.endFrame.setItemText(6, _translate("Form", "48000"))
        self.endFrame.setItemText(7, _translate("Form", "56000"))
        self.endFrame.setItemText(8, _translate("Form", "64000"))
        self.endFrame.setItemText(9, _translate("Form", "72000"))
        self.endFrame.setItemText(10, _translate("Form", "80954"))
        self.okButton.setText(_translate("Form", "OK"))
        self.startButton.setText(_translate("Form", "Start"))
        self.stopButton.setText(_translate("Form", "Stop"))
        self.exit_Button.setText(_translate("Form", "X"))
        self.min_Button.setText(_translate("Form", "-"))

import resource_rc
